<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Waypoint.Core\Waypoint.Core.csproj" />
    <ProjectReference Include="..\Waypoint.Sources\Waypoint.Sources.csproj" />
    <ProjectReference Include="..\Waypoint.Platform\Waypoint.Platform.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
