[package]
name = "waypoint-gui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "waypoint-gui"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14.0", features = ["debug"] }
serde_json.workspace = true
waypoint-cli = { path = "../cli" }
waypoint-core = { path = "../core" }
waypoint-engine = { path = "../engine" }
waypoint-platform = { path = "../platform" }
