# Provisions the self-signed development signing identity and points the build
# at it, so `dotnet publish` signs without anyone remembering an env var.
#
# Development only. A self-signed cert proves the signing pipeline works; it
# earns no SmartScreen/AV reputation. Re-run with the real OV/EV thumbprint
# (-Thumbprint) once one is available.

[CmdletBinding()]
param(
    [string]$Thumbprint,
    [string]$Subject = 'CN=Waypoint Driver Manager (Development - Self-Signed)'
)

$ErrorActionPreference = 'Stop'

$propsPath = Join-Path $PSScriptRoot 'Directory.Build.local.props'

if (-not $Thumbprint) {
    $existing =
        Get-ChildItem Cert:\CurrentUser\My |
        Where-Object {
            $_.Subject -eq $Subject -and
            $_.NotAfter -gt (Get-Date) -and
            $_.HasPrivateKey -and
            $_.EnhancedKeyUsageList.FriendlyName -contains 'Code Signing'
        } |
        Sort-Object NotAfter -Descending |
        Select-Object -First 1

    if ($existing) {
        Write-Host "Reusing existing development certificate."
        $Thumbprint = $existing.Thumbprint
    }
    else {
        Write-Host "Creating a self-signed development certificate..."
        $created = New-SelfSignedCertificate `
            -Type CodeSigningCert `
            -Subject $Subject `
            -CertStoreLocation Cert:\CurrentUser\My `
            -KeyUsage DigitalSignature `
            -KeyLength 3072 `
            -HashAlgorithm SHA256 `
            -NotAfter (Get-Date).AddYears(3)
        $Thumbprint = $created.Thumbprint
    }
}

# Condition so an explicit /p:WaypointSignThumbprint or the environment variable
# still wins over this file.
@"
<Project>
  <!-- Generated by setup-dev-signing.ps1. Gitignored: machine-local, not shared. -->
  <PropertyGroup>
    <WaypointSignThumbprint Condition="'`$(WaypointSignThumbprint)' == ''">$Thumbprint</WaypointSignThumbprint>
  </PropertyGroup>
</Project>
"@ | Set-Content -Path $propsPath -Encoding utf8

Write-Host ""
Write-Host "Thumbprint : $Thumbprint"
Write-Host "Wrote      : $propsPath"
Write-Host ""
Write-Host "`dotnet publish` will now sign automatically."
Write-Host "Self-signed: the chain reports UntrustedRoot and AV reputation is unvalidated."
